packages: []
allowBuilds:
  "@ffmpeg-installer/darwin-arm64": true
  "@livekit/local-inference": true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
patchedDependencies:
  "@livekit/agents-plugin-assemblyai@1.4.8": patches/@livekit__agents-plugin-assemblyai@1.4.8.patch
