packages: []
allowBuilds:
  "@ffmpeg-installer/darwin-arm64": true
  "@livekit/local-inference": true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
patchedDependencies:
  "@livekit/agents@1.6.2": patches/@livekit__agents@1.6.2.patch
